from sqlalchemy import inspect, text


COLUMN_STATEMENTS = (
    (
        "organizations",
        "billing_offer_version",
        "ALTER TABLE organizations ADD COLUMN billing_offer_version VARCHAR(80) NOT NULL DEFAULT 'legacy-v1'",
    ),
    (
        "organization_subscriptions",
        "activation_fee_paid_at",
        "ALTER TABLE organization_subscriptions ADD COLUMN activation_fee_paid_at TIMESTAMP",
    ),
    (
        "organization_subscriptions",
        "activation_price_id",
        "ALTER TABLE organization_subscriptions ADD COLUMN activation_price_id VARCHAR(80)",
    ),
    (
        "organization_subscriptions",
        "activation_payment_intent_id",
        "ALTER TABLE organization_subscriptions ADD COLUMN activation_payment_intent_id VARCHAR(80)",
    ),
    (
        "organization_subscriptions",
        "activation_invoice_id",
        "ALTER TABLE organization_subscriptions ADD COLUMN activation_invoice_id VARCHAR(80)",
    ),
    (
        "organization_subscriptions",
        "offer_version",
        "ALTER TABLE organization_subscriptions ADD COLUMN offer_version VARCHAR(80)",
    ),
    (
        "organization_subscriptions",
        "last_stripe_event_created_at",
        "ALTER TABLE organization_subscriptions ADD COLUMN last_stripe_event_created_at TIMESTAMP",
    ),
    (
        "organization_subscriptions",
        "last_stripe_event_id",
        "ALTER TABLE organization_subscriptions ADD COLUMN last_stripe_event_id VARCHAR(80)",
    ),
    (
        "organization_messaging_profiles",
        "cutover_state_json",
        "ALTER TABLE organization_messaging_profiles ADD COLUMN cutover_state_json TEXT",
    ),
    (
        "organization_a2p_onboardings",
        "provisioning_state_json",
        "ALTER TABLE organization_a2p_onboardings ADD COLUMN provisioning_state_json TEXT",
    ),
    (
        "organization_usage_billing_periods",
        "stripe_invoice_id",
        "ALTER TABLE organization_usage_billing_periods ADD COLUMN stripe_invoice_id VARCHAR(80)",
    ),
    (
        "organization_usage_billing_periods",
        "invoiced_units",
        "ALTER TABLE organization_usage_billing_periods ADD COLUMN invoiced_units INTEGER NOT NULL DEFAULT 0",
    ),
    (
        "organization_usage_billing_periods",
        "settlement_version",
        "ALTER TABLE organization_usage_billing_periods ADD COLUMN settlement_version INTEGER NOT NULL DEFAULT 0",
    ),
    (
        "organization_usage_billing_periods",
        "settlement_due_at",
        "ALTER TABLE organization_usage_billing_periods ADD COLUMN settlement_due_at TIMESTAMP",
    ),
    (
        "pilot_applications",
        "owner_invitation_id",
        "ALTER TABLE pilot_applications ADD COLUMN owner_invitation_id INTEGER REFERENCES organization_invitations (id)",
    ),
    (
        "customer_policy_acceptances",
        "policy_name",
        "ALTER TABLE customer_policy_acceptances ADD COLUMN policy_name VARCHAR(40) NOT NULL DEFAULT 'legacy_bundle'",
    ),
    (
        "external_webhook_deliveries",
        "resource_key",
        "ALTER TABLE external_webhook_deliveries ADD COLUMN resource_key VARCHAR(200)",
    ),
    (
        "external_webhook_deliveries",
        "response_json",
        "ALTER TABLE external_webhook_deliveries ADD COLUMN response_json TEXT",
    ),
)


TABLE_DEFINITIONS = (
    (
        "pilot_applications",
        """
        CREATE TABLE pilot_applications (
            id INTEGER PRIMARY KEY,
            business_name VARCHAR(120) NOT NULL,
            contact_name VARCHAR(120) NOT NULL,
            email VARCHAR(255) NOT NULL,
            phone VARCHAR(20),
            website_url VARCHAR(255),
            use_case TEXT NOT NULL,
            expected_monthly_segments INTEGER,
            twilio_account_status VARCHAR(40),
            status VARCHAR(20) NOT NULL DEFAULT 'new',
            source_ip_hash VARCHAR(64) NOT NULL,
            user_agent VARCHAR(255),
            reviewed_by_user_id INTEGER,
            reviewed_at TIMESTAMP,
            review_note TEXT,
            organization_id INTEGER,
            owner_invitation_id INTEGER,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            FOREIGN KEY(reviewed_by_user_id) REFERENCES users (id),
            FOREIGN KEY(organization_id) REFERENCES organizations (id),
            FOREIGN KEY(owner_invitation_id) REFERENCES organization_invitations (id)
        )
        """,
        """
        CREATE TABLE pilot_applications (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_name VARCHAR(120) NOT NULL,
            contact_name VARCHAR(120) NOT NULL,
            email VARCHAR(255) NOT NULL,
            phone VARCHAR(20),
            website_url VARCHAR(255),
            use_case TEXT NOT NULL,
            expected_monthly_segments INTEGER,
            twilio_account_status VARCHAR(40),
            status VARCHAR(20) NOT NULL DEFAULT 'new',
            source_ip_hash VARCHAR(64) NOT NULL,
            user_agent VARCHAR(255),
            reviewed_by_user_id INTEGER REFERENCES users (id),
            reviewed_at TIMESTAMP,
            review_note TEXT,
            organization_id INTEGER REFERENCES organizations (id),
            owner_invitation_id INTEGER UNIQUE REFERENCES organization_invitations (id),
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )
        """,
    ),
    (
        "customer_policy_acceptances",
        """
        CREATE TABLE customer_policy_acceptances (
            id INTEGER PRIMARY KEY,
            organization_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            policy_name VARCHAR(40) NOT NULL,
            policy_version VARCHAR(80) NOT NULL,
            accepted_ip VARCHAR(45),
            accepted_user_agent VARCHAR(255),
            accepted_at TIMESTAMP NOT NULL,
            FOREIGN KEY(organization_id) REFERENCES organizations (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
        """,
        """
        CREATE TABLE customer_policy_acceptances (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            organization_id INTEGER NOT NULL REFERENCES organizations (id),
            user_id INTEGER NOT NULL REFERENCES users (id),
            policy_name VARCHAR(40) NOT NULL,
            policy_version VARCHAR(80) NOT NULL,
            accepted_ip VARCHAR(45),
            accepted_user_agent VARCHAR(255),
            accepted_at TIMESTAMP NOT NULL
        )
        """,
    ),
    (
        "pilot_application_status_history",
        """
        CREATE TABLE pilot_application_status_history (
            id INTEGER PRIMARY KEY,
            pilot_application_id INTEGER NOT NULL,
            from_status VARCHAR(20),
            to_status VARCHAR(20) NOT NULL,
            actor_user_id INTEGER,
            note TEXT,
            created_at TIMESTAMP NOT NULL,
            FOREIGN KEY(pilot_application_id) REFERENCES pilot_applications (id),
            FOREIGN KEY(actor_user_id) REFERENCES users (id)
        )
        """,
        """
        CREATE TABLE pilot_application_status_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pilot_application_id INTEGER NOT NULL REFERENCES pilot_applications (id),
            from_status VARCHAR(20),
            to_status VARCHAR(20) NOT NULL,
            actor_user_id INTEGER REFERENCES users (id),
            note TEXT,
            created_at TIMESTAMP NOT NULL
        )
        """,
    ),
    (
        "stripe_checkout_sessions",
        """
        CREATE TABLE stripe_checkout_sessions (
            id INTEGER PRIMARY KEY,
            organization_id INTEGER NOT NULL,
            stripe_checkout_session_id VARCHAR(80) NOT NULL,
            billing_plan_code VARCHAR(30) NOT NULL,
            recurring_price_id VARCHAR(80) NOT NULL,
            activation_price_id VARCHAR(80),
            offer_version VARCHAR(80) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'open',
            stripe_customer_id VARCHAR(80),
            stripe_subscription_id VARCHAR(80),
            created_at TIMESTAMP NOT NULL,
            completed_at TIMESTAMP,
            expired_at TIMESTAMP,
            FOREIGN KEY(organization_id) REFERENCES organizations (id)
        )
        """,
        """
        CREATE TABLE stripe_checkout_sessions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            organization_id INTEGER NOT NULL REFERENCES organizations (id),
            stripe_checkout_session_id VARCHAR(80) NOT NULL,
            billing_plan_code VARCHAR(30) NOT NULL,
            recurring_price_id VARCHAR(80) NOT NULL,
            activation_price_id VARCHAR(80),
            offer_version VARCHAR(80) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'open',
            stripe_customer_id VARCHAR(80),
            stripe_subscription_id VARCHAR(80),
            created_at TIMESTAMP NOT NULL,
            completed_at TIMESTAMP,
            expired_at TIMESTAMP
        )
        """,
    ),
    (
        "external_webhook_deliveries",
        """
        CREATE TABLE external_webhook_deliveries (
            id INTEGER PRIMARY KEY,
            provider VARCHAR(30) NOT NULL,
            delivery_id VARCHAR(160) NOT NULL,
            organization_id INTEGER,
            resource_key VARCHAR(200),
            payload_digest VARCHAR(64) NOT NULL,
            source_revision_at TIMESTAMP,
            status VARCHAR(20) NOT NULL DEFAULT 'processing',
            received_at TIMESTAMP NOT NULL,
            processed_at TIMESTAMP,
            last_error TEXT,
            response_json TEXT,
            FOREIGN KEY(organization_id) REFERENCES organizations (id)
        )
        """,
        """
        CREATE TABLE external_webhook_deliveries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider VARCHAR(30) NOT NULL,
            delivery_id VARCHAR(160) NOT NULL,
            organization_id INTEGER REFERENCES organizations (id),
            resource_key VARCHAR(200),
            payload_digest VARCHAR(64) NOT NULL,
            source_revision_at TIMESTAMP,
            status VARCHAR(20) NOT NULL DEFAULT 'processing',
            received_at TIMESTAMP NOT NULL,
            processed_at TIMESTAMP,
            last_error TEXT,
            response_json TEXT
        )
        """,
    ),
    (
        "message_dispatch_attempts",
        """
        CREATE TABLE message_dispatch_attempts (
            id INTEGER PRIMARY KEY,
            organization_id INTEGER NOT NULL,
            message_log_id INTEGER,
            scheduled_message_id INTEGER,
            logical_send_key VARCHAR(128) NOT NULL,
            recipient_phone VARCHAR(20) NOT NULL,
            message_body_digest VARCHAR(64) NOT NULL,
            send_kind VARCHAR(30) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'queued',
            provider_message_sid VARCHAR(64),
            attempt_count INTEGER NOT NULL DEFAULT 0,
            last_error TEXT,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            sending_at TIMESTAMP,
            resolved_at TIMESTAMP,
            FOREIGN KEY(organization_id) REFERENCES organizations (id),
            FOREIGN KEY(message_log_id) REFERENCES message_logs (id),
            FOREIGN KEY(scheduled_message_id) REFERENCES scheduled_messages (id)
        )
        """,
        """
        CREATE TABLE message_dispatch_attempts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            organization_id INTEGER NOT NULL REFERENCES organizations (id),
            message_log_id INTEGER REFERENCES message_logs (id),
            scheduled_message_id INTEGER REFERENCES scheduled_messages (id),
            logical_send_key VARCHAR(128) NOT NULL,
            recipient_phone VARCHAR(20) NOT NULL,
            message_body_digest VARCHAR(64) NOT NULL,
            send_kind VARCHAR(30) NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT 'queued',
            provider_message_sid VARCHAR(64),
            attempt_count INTEGER NOT NULL DEFAULT 0,
            last_error TEXT,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL,
            sending_at TIMESTAMP,
            resolved_at TIMESTAMP
        )
        """,
    ),
)


INDEX_STATEMENTS = (
    "CREATE INDEX IF NOT EXISTS ix_pilot_applications_email ON pilot_applications (email)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_applications_status ON pilot_applications (status)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_applications_source_ip_hash ON pilot_applications (source_ip_hash)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_applications_created_at ON pilot_applications (created_at)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_policy_acceptance_org_user_name_version ON customer_policy_acceptances (organization_id, user_id, policy_name, policy_version)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_pilot_applications_owner_invitation_id ON pilot_applications (owner_invitation_id)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_application_status_history_application_id ON pilot_application_status_history (pilot_application_id)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_application_status_history_to_status ON pilot_application_status_history (to_status)",
    "CREATE INDEX IF NOT EXISTS ix_pilot_application_status_history_created_at ON pilot_application_status_history (created_at)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_stripe_checkout_session_id ON stripe_checkout_sessions (stripe_checkout_session_id)",
    "CREATE INDEX IF NOT EXISTS ix_stripe_checkout_sessions_organization_id ON stripe_checkout_sessions (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_stripe_checkout_sessions_status ON stripe_checkout_sessions (status)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_external_webhook_provider_delivery ON external_webhook_deliveries (provider, delivery_id)",
    "CREATE INDEX IF NOT EXISTS ix_external_webhook_deliveries_organization_id ON external_webhook_deliveries (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_external_webhook_deliveries_resource_key ON external_webhook_deliveries (resource_key)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_message_dispatch_logical_send_key ON message_dispatch_attempts (logical_send_key)",
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_message_dispatch_provider_sid ON message_dispatch_attempts (provider_message_sid)",
    "CREATE INDEX IF NOT EXISTS ix_message_dispatch_organization_id ON message_dispatch_attempts (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_message_dispatch_message_log_id ON message_dispatch_attempts (message_log_id)",
    "CREATE INDEX IF NOT EXISTS ix_message_dispatch_scheduled_message_id ON message_dispatch_attempts (scheduled_message_id)",
    "CREATE INDEX IF NOT EXISTS ix_message_dispatch_status ON message_dispatch_attempts (status)",
    "CREATE INDEX IF NOT EXISTS ix_org_subscriptions_activation_payment_intent ON organization_subscriptions (activation_payment_intent_id)",
    "CREATE INDEX IF NOT EXISTS ix_org_subscriptions_activation_invoice ON organization_subscriptions (activation_invoice_id)",
    "CREATE INDEX IF NOT EXISTS ix_org_usage_periods_invoice_id ON organization_usage_billing_periods (stripe_invoice_id)",
    "CREATE INDEX IF NOT EXISTS ix_org_usage_periods_settlement_due_at ON organization_usage_billing_periods (settlement_due_at)",
)


def _table_exists(connection, table_name: str) -> bool:
    return table_name in inspect(connection).get_table_names()


def _column_names(connection, table_name: str) -> set[str]:
    if not _table_exists(connection, table_name):
        return set()
    return {column["name"] for column in inspect(connection).get_columns(table_name)}


def _ensure_column(connection, table_name: str, column_name: str, statement: str, logger) -> None:
    columns = _column_names(connection, table_name)
    if not columns:
        logger.info("SaaS migration 018: table %s missing, skipping column %s.", table_name, column_name)
        return
    if column_name in columns:
        logger.info("SaaS migration 018: %s.%s already exists.", table_name, column_name)
        return
    connection.execute(text(statement))
    logger.info("SaaS migration 018: added %s.%s.", table_name, column_name)


def _ensure_table(
    connection,
    table_name: str,
    sqlite_statement: str,
    postgres_statement: str,
    logger,
) -> None:
    if _table_exists(connection, table_name):
        logger.info("SaaS migration 018: table %s already exists.", table_name)
        return
    statement = postgres_statement if connection.dialect.name == "postgresql" else sqlite_statement
    connection.execute(text(statement))
    logger.info("SaaS migration 018: created table %s.", table_name)


def apply(connection, logger) -> None:
    for table_name, column_name, statement in COLUMN_STATEMENTS:
        _ensure_column(connection, table_name, column_name, statement, logger)

    for table_name, sqlite_statement, postgres_statement in TABLE_DEFINITIONS:
        _ensure_table(
            connection,
            table_name,
            sqlite_statement,
            postgres_statement,
            logger,
        )

    tables = set(inspect(connection).get_table_names())
    for statement in INDEX_STATEMENTS:
        target_table = statement.rsplit(" ON ", 1)[-1].split(" ", 1)[0]
        if target_table in tables:
            connection.execute(text(statement))
    logger.info("SaaS migration 018: ensured managed-pilot indexes.")
