// <auto-generated />
using AOC_SMS.UI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AOC_SMS.UI.Migrations
{
    [DbContext(typeof(AocSmsDbContext))]
    [Migration("20251229041925_InitialRecipients")]
    partial class InitialRecipients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsOptedOut")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneE164")
                        .IsUnique();

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientListEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RecipientLists");
                });

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientListMemberEntity", b =>
                {
                    b.Property<long>("RecipientListId")
                        .HasColumnType("bigint");

                    b.Property<long>("RecipientId")
                        .HasColumnType("bigint");

                    b.HasKey("RecipientListId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("RecipientListMembers");
                });

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientListMemberEntity", b =>
                {
                    b.HasOne("AOC_SMS.UI.Data.Entities.RecipientEntity", "Recipient")
                        .WithMany("ListMemberships")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AOC_SMS.UI.Data.Entities.RecipientListEntity", "RecipientList")
                        .WithMany("Members")
                        .HasForeignKey("RecipientListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("RecipientList");
                });

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientEntity", b =>
                {
                    b.Navigation("ListMemberships");
                });

            modelBuilder.Entity("AOC_SMS.UI.Data.Entities.RecipientListEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
